subject = "new_turn"
when = "When: "
game = "Game Name: "
player = "Player Name: "
turn = "Turn Number: "
path_to_player_aliases = r"notes/player aliases.csv"
path_to_game_aliases = r"notes/game aliases.csv"
overflow_channel_name = "Overflow"
